name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build -f Dockerfile.api -t ghcr.io/${{ github.repository }}/horizon-api:latest .
          docker tag ghcr.io/${{ github.repository }}/horizon-api:latest ghcr.io/${{ github.repository }}/horizon-api:${{ github.sha }}

      - name: Build App image
        run: |
          docker build -f Dockerfile.app -t ghcr.io/${{ github.repository }}/horizon-app:latest .
          docker tag ghcr.io/${{ github.repository }}/horizon-app:latest ghcr.io/${{ github.repository }}/horizon-app:${{ github.sha }}

      - name: Push API images
        run: |
          docker push ghcr.io/${{ github.repository }}/horizon-api:latest
          docker push ghcr.io/${{ github.repository }}/horizon-api:${{ github.sha }}

      - name: Push App images
        run: |
          docker push ghcr.io/${{ github.repository }}/horizon-app:latest
          docker push ghcr.io/${{ github.repository }}/horizon-app:${{ github.sha }}